const ERROR_INVALID_DATA = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_ACCESS_DENIED = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;

module.exports = {
  ERROR_INVALID_DATA,
  ERROR_UNAUTHORIZED,
  ERROR_ACCESS_DENIED,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
};